### ISSUE TITLE
Why "num_actions=47"?

### ISSUE THREAD

**Issue by meyenii** [DelphianCalamity/ReJOIN#1]
Thanks for sharing the reimplementation.

I have a question about action space.
There are 21 relations in Join Order Benchmark.
I think the following can be considered as the design of the action space.

- Pair of 21 actions
- Combination of all relations: (21 * 20) / 2
- Possible Joins: 22 (As mentioned in your report)

It seems like the number "47" in environment.py does not correspond to any of them.
How was this number determined?

Thank you in advance.

**Comment by antonismand** [comment]
Hi meyenii,

In order to improve our results we further reduced the action space by exploiting the information provided from the ER diagram.
See here: [https://www.researchgate.net/profile/Peter_Boncz/publication/319893076/figure/fig2/AS:631637725438007@1527605577677/MDB-schema-with-key-foreign-key-relationships-Underlined-attributes-are-primary-keys.png](https://www.researchgate.net/profile/Peter_Boncz/publication/319893076/figure/fig2/AS:631637725438007@1527605577677/MDB-schema-with-key-foreign-key-relationships-Underlined-attributes-are-primary-keys.png)
With this way we calculated the actual number of possible joins in the specific dataset.
The calculation is included in the file main_testing.py.

Thank you
